export const BOOK_AN_EVENT = 'BOOK_AN_EVENT'
export const PUT_EVENT_DETAILS = 'PUT_EVENT_DETAILS'
export const BOOKA_PLACE = 'BOOKA_PLACE'
export const FRIENDS = 'FRIENDS'
export const SEARCH = 'SEARCH'
export const MY_PROFILE = 'MY_PROFILE'
export const MY_HOST_PROFILE = 'MY_HOST_PROFILE'
export const MY_PROFILE_UPDATE = 'MY_PROFILE_UPDATE'
export const REGISTER_NEW_PREMISES = 'REGISTER_NEW_PREMISES'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const GO_TO_HOME = 'GO_TO_HOME'


